# Generated by Django 3.1.6 on 2021-05-11 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Your name here', max_length=255)),
                ('Email', models.EmailField(default='example@host.com', max_length=255)),
                ('Category', models.CharField(choices=[('Criminal Case', 'Criminal Case'), ('Civil Case', 'Civil Case'), ('Marriage Dissolution', 'Marriage Dissolution'), ('Paternity and Child Custody', 'Paternity and Child Custody'), ('Protection Orders Aganist Domestic Violence', 'Protection Orders Aganist Domestic Violence'), ('Name Changes', 'Name Changes'), ('Guardianship', 'Guardianship'), ('Termination of Parental Rights and Adoptions', 'Termination of Parental Rights and Adoptions'), ('Juvenile Matters', 'Juvenile Matters'), ('Emancipation and Approval of Underage Marriages', 'Emancipation and Approval of Underage Marriages')], default='Criminal Case', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(default='your name', max_length=255)),
                ('email', models.EmailField(default='example@host.com', max_length=255)),
                ('contact_no', models.IntegerField(default=911234567890)),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='lawyer_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='your name', max_length=255)),
                ('Email', models.CharField(default='example@host.com', max_length=255)),
                ('Phone_No', models.CharField(default=911234567890, max_length=13)),
                ('Profile_Photo', models.ImageField(null=True, upload_to='profile')),
                ('Case', models.CharField(default='your case fought, here', max_length=255)),
                ('General_Fee', models.IntegerField(default=1000)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.category')),
            ],
        ),
        migrations.CreateModel(
            name='Cases_Fought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Summary', models.TextField()),
                ('Email', models.CharField(default='example@host.com', max_length=255)),
                ('Cases', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.lawyer_profile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.category')),
            ],
        ),
    ]
