# Generated by Django 3.1.6 on 2021-05-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer_profile',
            name='Case',
        ),
        migrations.AddField(
            model_name='lawyer_profile',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50),
        ),
    ]
