# Generated by Django 3.1.6 on 2021-05-16 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='User_name',
            new_name='Username',
        ),
    ]
