# Generated by Django 3.1.6 on 2021-05-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer_profile',
            name='Bio',
            field=models.TextField(default='Bio'),
        ),
    ]
