# Generated by Django 3.1.6 on 2021-05-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210511_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category',
            field=models.IntegerField(choices=[(1, 'Criminal Case'), (2, 'Civil Case'), (3, 'Marriage Dissolution'), (4, 'Paternity and Child Custody'), (5, 'Protection Orders Aganist Domestic Violence'), (6, 'Name Changes'), (7, 'Guardianship'), (8, 'Termination of Parental Rights and Adoptions'), (9, 'Juvenile Matters'), (10, 'Emancipation and Approval of Underage Marriages.')], default='Criminal Case', max_length=10),
        ),
    ]
