# Generated by Django 3.1.6 on 2021-05-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_lawyer_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=255),
        ),
    ]
