# Generated by Django 3.1.6 on 2021-05-31 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210531_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases_fought',
            name='case',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cases_fought',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.lawyer'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1),
        ),
    ]
