# Generated by Django 3.1.6 on 2021-05-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cases_fought',
            old_name='Cases',
            new_name='Case',
        ),
    ]
