# Generated by Django 3.1.6 on 2021-05-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210527_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=2, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
