# Generated by Django 3.1.6 on 2021-06-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210615_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases_fought',
            name='uploaded_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
