# Generated by Django 3.1.6 on 2021-06-26 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210622_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='designation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='lawyertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.category'),
        ),
    ]
