# Generated by Django 3.1.6 on 2021-06-28 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210628_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='lawyertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.category'),
        ),
    ]
