# Generated by Django 3.1.6 on 2021-06-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210628_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='lawyertype',
            field=models.CharField(default='', max_length=50),
        ),
    ]
