# Generated by Django 3.1.6 on 2021-05-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewcases',
            old_name='Case',
            new_name='case',
        ),
    ]
