# Generated by Django 3.2 on 2021-04-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='category',
            field=models.IntegerField(choices=[(1, 'image'), (2, 'text'), (3, 'nlp'), (4, 'video'), (5, 'others')], default='image'),
        ),
    ]
