# Generated by Django 3.1.6 on 2021-05-27 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210527_1444'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='user',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='users.client'),
        ),
        migrations.AddField(
            model_name='reviewcases',
            name='reviewer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.client'),
            preserve_default=False,
        ),
    ]
