# Generated by Django 3.1.6 on 2021-05-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_aimodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseName', models.CharField(default='Case', max_length=255)),
                ('description', models.TextField()),
                ('category', models.IntegerField(choices=[(1, 'image'), (2, 'text'), (3, 'nlp'), (4, 'video'), (5, 'others')], default='image')),
                ('model_image', models.ImageField(null=True, upload_to='ai_models/images')),
            ],
        ),
        migrations.DeleteModel(
            name='AiModel',
        ),
    ]
