# Generated by Django 3.1.6 on 2021-06-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20210603_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='contact_No',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
