# Generated by Django 3.1.6 on 2021-05-10 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20210510_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cases',
            old_name='caseName',
            new_name='CaseName',
        ),
        migrations.RenameField(
            model_name='cases',
            old_name='model_image',
            new_name='Case_image',
        ),
    ]
