# Generated by Django 3.1.6 on 2021-05-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20210510_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cases',
            old_name='CaseName',
            new_name='Case_Name',
        ),
    ]
