# Generated by Django 3.1.6 on 2021-05-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_auto_20210510_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='Contact_No',
            field=models.IntegerField(default=911234567890, unique=True),
        ),
    ]
