# Generated by Django 3.1.6 on 2021-05-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_auto_20210511_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='Contact_No',
            field=models.IntegerField(max_length=13),
        ),
    ]
