# Generated by Django 3.1.6 on 2021-05-10 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_auto_20210511_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='Contact_No',
        ),
    ]
