# Generated by Django 3.1.6 on 2021-05-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_remove_cases_contact_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cases',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='cases',
            old_name='description',
            new_name='Description',
        ),
        migrations.AddField(
            model_name='cases',
            name='Contact_No',
            field=models.IntegerField(default=911234567890, max_length=12, unique=True),
        ),
    ]
