# Generated by Django 3.1.6 on 2021-05-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_auto_20210511_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='Name',
            field=models.CharField(default='your name', max_length=255),
        ),
    ]
