# Generated by Django 3.1.6 on 2021-05-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_cases_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='email',
            field=models.EmailField(default='example@host.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='cases',
            name='Case_image',
            field=models.ImageField(null=True, upload_to='Case_dir/images'),
        ),
    ]
