# Generated by Django 3.1.6 on 2021-05-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_auto_20210511_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='Contact_No',
            field=models.IntegerField(default=911234567890, unique=True),
        ),
    ]
