# Generated by Django 3.1.6 on 2021-05-11 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('storage', '0016_auto_20210511_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='Name',
            field=models.ForeignKey(default='your name', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='users.user_profile'),
        ),
    ]
